#!/bin/bash

GTSIPATH="graphes/GTSI-grap"
disasPATH=$HOME"/disasm/disasm.py"
pattern=$1
test=$2
verbose=$3
tshort=`echo $test | sed 's:.*/::g'`

testdot=`mktemp -u /tmp/$tshort-XXX.dot`
cd /tmp; rm -f $testdot; cd - > /dev/null

if [ "$verbose" = "-v" ]; then
	set -x
fi

if [ ! "$verbose" = "-q" ]; then
	echo "Disassembling "$test" (to "$testdot"):"
fi
python2 $disasPATH $verbose -f $testdot $test

if [ ! "$verbose" = "-q" ]; then
	echo ""
	echo "Looking for pattern ("$pattern") in "$test":"
fi
./$GTSIPATH $verbose $pattern $testdot

